In [12]:
for a in range(10):
    print(a)

0
1
2
3
4
5
6
7
8
9


In [13]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [14]:
A = np.matrix("[1 2 3; 4 5 6; 3 2 1]")
print(A)

[[1 2 3]
 [4 5 6]
 [3 2 1]]


In [15]:
A.diagonal()

matrix([[1, 5, 1]])

In [16]:
a = np.array([1,2,3])

In [17]:
import numpy as np

In [18]:
np.array([1,2,3,4,5]) ** 2

array([ 1,  4,  9, 16, 25])

In [19]:
clear

In [50]:
import time
x = np.random.rand(1000000)
y = np.random.rand(1000000)
tic = time.time()
z = x.dot(y)
toc = time.time()
print (str((toc - tic) * 1000) + " ms")

1.3000965118408203 ms


In [2]:
print("Hello World")

Hello World
